package domain;

// Generated 3 févr. 2016 19:16:46 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Gene generated by hbm2java
 */
@Entity
@Table(name = "gene")
@XmlRootElement	(name ="gene")
public class Gene implements java.io.Serializable {

	private String geneId;
	private short version;
	private String source;
	private String objectType;
	private String logicName;
	private String species;
	private String description;
	private String displayName;
	private String assemblyName;
	private String biotype;
	private int end;
	private String dbType;
	private short strand;
	private int start;
	private String seqRegionName;
	private Set<Comptage> comptages = new HashSet<Comptage>(0);

	public Gene() {
	}

	public Gene(String geneId) {
		this.geneId = geneId;
	}

	public Gene(String geneId, short version, String source, String objectType,
			String logicName, String species, String description,
			String displayName, String assemblyName, String biotype,
			int end, String dbType, short strand, int start,
			String seqRegionName, Set<Comptage> comptages) {
		this.geneId = geneId;
		this.version = version;
		this.source = source;
		this.objectType = objectType;
		this.logicName = logicName;
		this.species = species;
		this.description = description;
		this.displayName = displayName;
		this.assemblyName = assemblyName;
		this.biotype = biotype;
		this.end = end;
		this.dbType = dbType;
		this.strand = strand;
		this.start = start;
		this.seqRegionName = seqRegionName;
		this.comptages = comptages;
	}

	@Id
	@Column(name = "gene_id", unique = true, nullable = false, length = 25)
	public String getGeneId() {
		return this.geneId;
	}

	public void setGeneId(String geneId) {
		this.geneId = geneId;
	}

	@Version
	@Column(name = "version")
	public short getVersion() {
		return this.version;
	}

	public void setVersion(short version) {
		this.version = version;
	}

	@Column(name = "source", length = 50)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "object_type", length = 50)
	public String getObjectType() {
		return this.objectType;
	}

	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}

	@Column(name = "logic_name", length = 50)
	public String getLogicName() {
		return this.logicName;
	}

	public void setLogicName(String logicName) {
		this.logicName = logicName;
	}

	@Column(name = "species", length = 50)
	public String getSpecies() {
		return this.species;
	}

	public void setSpecies(String species) {
		this.species = species;
	}

	@Column(name = "description", length = 150)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "display_name", length = 50)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "assembly_name", length = 50)
	public String getAssemblyName() {
		return this.assemblyName;
	}

	public void setAssemblyName(String assemblyName) {
		this.assemblyName = assemblyName;
	}

	@Column(name = "biotype", length = 50)
	public String getBiotype() {
		return this.biotype;
	}

	public void setBiotype(String biotype) {
		this.biotype = biotype;
	}

	@Column(name = "end")
	public int getEnd() {
		return this.end;
	}

	public void setEnd(int end) {
		this.end = end;
	}

	@Column(name = "db_type", length = 50)
	public String getDbType() {
		return this.dbType;
	}

	public void setDbType(String dbType) {
		this.dbType = dbType;
	}

	@Column(name = "strand")
	public short getStrand() {
		return this.strand;
	}

	public void setStrand(short strand) {
		this.strand = strand;
	}

	@Column(name = "start")
	public int getStart() {
		return this.start;
	}

	public void setStart(int start) {
		this.start = start;
	}

	@Column(name = "seq_region_name", length = 5)
	public String getSeqRegionName() {
		return this.seqRegionName;
	}

	public void setSeqRegionName(String seqRegionName) {
		this.seqRegionName = seqRegionName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gene")
	@JoinColumn(name = "gene_id", nullable = false, insertable = false, updatable = false)
	@XmlTransient
	public Set<Comptage> getComptages() {
		return this.comptages;
	}

	public void setComptages(Set<Comptage> comptages) {
		this.comptages = comptages;
	}

}
