package domain;

// Generated 2 févr. 2016 10:59:52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Gene generated by hbm2java
 */
@Entity
@Table(name = "gene", schema = "public")
@XmlRootElement	(name ="gene")
public class Gene implements java.io.Serializable {

	private String geneId;
	private Short version;
	private String source;
	private String objectType;
	private String logicName;
	private String species;
	private String description;
	private String displayName;
	private String assemblyName;
	private String biotype;
	private Integer end;
	private String dbType;
	private Short strand;
	private Integer start;
	private String seqRegionName;
	private Set<Comptage> comptages = new HashSet<Comptage>(0);

	public Gene() {
	}

	public Gene(String geneId) {
		this.geneId = geneId;
	}

	public Gene(String geneId, String source, String objectType,
			String logicName, String species, String description,
			String displayName, String assemblyName, String biotype,
			Integer end, String dbType, Short strand, Integer start,
			String seqRegionName, Set<Comptage> comptages) {
		this.geneId = geneId;
		this.source = source;
		this.objectType = objectType;
		this.logicName = logicName;
		this.species = species;
		this.description = description;
		this.displayName = displayName;
		this.assemblyName = assemblyName;
		this.biotype = biotype;
		this.end = end;
		this.dbType = dbType;
		this.strand = strand;
		this.start = start;
		this.seqRegionName = seqRegionName;
		this.comptages = comptages;
	}

	@Id
	@Column(name = "gene_id", unique = true, nullable = false, length = 25)
	public String getGeneId() {
		return this.geneId;
	}

	public void setGeneId(String geneId) {
		this.geneId = geneId;
	}

	@Version
	@Column(name = "version")
	public Short getVersion() {
		return this.version;
	}

	public void setVersion(Short version) {
		this.version = version;
	}

	@Column(name = "source", length = 50)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "object_type", length = 50)
	public String getObjectType() {
		return this.objectType;
	}

	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}

	@Column(name = "logic_name", length = 50)
	public String getLogicName() {
		return this.logicName;
	}

	public void setLogicName(String logicName) {
		this.logicName = logicName;
	}

	@Column(name = "species", length = 50)
	public String getSpecies() {
		return this.species;
	}

	public void setSpecies(String species) {
		this.species = species;
	}

	@Column(name = "description", length = 150)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "display_name", length = 50)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "assembly_name", length = 50)
	public String getAssemblyName() {
		return this.assemblyName;
	}

	public void setAssemblyName(String assemblyName) {
		this.assemblyName = assemblyName;
	}

	@Column(name = "biotype", length = 50)
	public String getBiotype() {
		return this.biotype;
	}

	public void setBiotype(String biotype) {
		this.biotype = biotype;
	}

	@Column(name = "end")
	public Integer getEnd() {
		return this.end;
	}

	public void setEnd(Integer end) {
		this.end = end;
	}

	@Column(name = "db_type", length = 50)
	public String getDbType() {
		return this.dbType;
	}

	public void setDbType(String dbType) {
		this.dbType = dbType;
	}

	@Column(name = "strand")
	public Short getStrand() {
		return this.strand;
	}

	public void setStrand(Short strand) {
		this.strand = strand;
	}

	@Column(name = "start")
	public Integer getStart() {
		return this.start;
	}

	public void setStart(Integer start) {
		this.start = start;
	}

	@Column(name = "seq_region_name", length = 5)
	public String getSeqRegionName() {
		return this.seqRegionName;
	}

	public void setSeqRegionName(String seqRegionName) {
		this.seqRegionName = seqRegionName;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "gene")
	public Set<Comptage> getComptages() {
		return this.comptages;
	}

	public void setComptages(Set<Comptage> comptages) {
		this.comptages = comptages;
	}

}
