package domain;

// Generated 2 févr. 2016 10:59:52 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Matrix generated by hbm2java
 */
@Entity
@Table(name = "matrix", schema = "public")
@XmlRootElement	(name ="matrix")
public class Matrix implements java.io.Serializable {

	private short matrixId;
	private String description;
	private Set<Comptage> comptages = new HashSet<Comptage>(0);

	public Matrix() {
	}

	public Matrix(short matrixId, String description) {
		this.matrixId = matrixId;
		this.description = description;
	}

	public Matrix(short matrixId, String description, Set<Comptage> comptages) {
		this.matrixId = matrixId;
		this.description = description;
		this.comptages = comptages;
	}

	@Id
	@Column(name = "matrix_id", unique = true, nullable = false)
	public short getMatrixId() {
		return this.matrixId;
	}

	public void setMatrixId(short matrixId) {
		this.matrixId = matrixId;
	}

	@Column(name = "description", nullable = false, length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "matrix")
	public Set<Comptage> getComptages() {
		return this.comptages;
	}

	public void setComptages(Set<Comptage> comptages) {
		this.comptages = comptages;
	}

}
