package domain;

// Generated 3 févr. 2016 19:16:46 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Work generated by hbm2java
 */
@Entity
@Table(name = "work")
@XmlRootElement	(name ="work")
public class Work implements java.io.Serializable {

	private WorkId id;
	private Matrix matrix;
	private String idType;

	public Work() {
	}

	public Work(WorkId id, Matrix matrix, String idType) {
		this.id = id;
		this.matrix = matrix;
		this.idType = idType;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false, length = 25)),
			@AttributeOverride(name = "matrixId", column = @Column(name = "matrix_id", nullable = false)) })
	public WorkId getId() {
		return this.id;
	}

	public void setId(WorkId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "matrix_id", nullable = false, insertable = false, updatable = false)
	@XmlTransient
	public Matrix getMatrix() {
		return this.matrix;
	}

	public void setMatrix(Matrix matrix) {
		this.matrix = matrix;
	}

	@Column(name = "id_type", nullable = false, length = 1)
	public String getIdType() {
		return this.idType;
	}

	public void setIdType(String idType) {
		this.idType = idType;
	}

}
